# Generated by Django 5.0.6 on 2024-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.FileField(null=True, upload_to='media/images/'),
        ),
    ]
