# Generated by Django 5.0.6 on 2024-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
