# Generated by Django 5.0.6 on 2024-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
