# Generated by Django 5.0.6 on 2024-06-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0002_logo_upload_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logo',
            new_name='limage',
        ),
        migrations.RenameField(
            model_name='limage',
            old_name='logo',
            new_name='image',
        ),
    ]
