# Generated by Django 5.0.6 on 2024-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0003_rename_logo_limage_rename_logo_limage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limage',
            name='upload_at',
        ),
        migrations.AlterField(
            model_name='limage',
            name='image',
            field=models.FileField(blank=True, help_text='Logo Must Be Only One Image', null=True, upload_to='logo/'),
        ),
    ]
