# Generated by Django 5.0.6 on 2024-06-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
