# Generated by Django 5.0.6 on 2024-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_nav_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='url',
            field=models.URLField(),
        ),
    ]
