# Generated by Django 5.0.6 on 2024-06-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_alter_nav_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='order',
        ),
    ]
