# Generated by Django 5.0.6 on 2024-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='sec-banner/'),
        ),
    ]
