# Generated by Django 5.0.6 on 2024-06-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.FileField(null=True, upload_to='sec-banner/'),
        ),
    ]
