# Generated by Django 5.0.6 on 2024-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_remove_banner_banner_image_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(help_text='Max Resolutions (1460 × 822)', null=True, upload_to='secbanner/'),
        ),
    ]
