# Generated by Django 5.0.6 on 2024-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_rating_products_total_amount_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
