# Generated by Django 5.0.6 on 2024-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_rating_products_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
