# Generated by Django 5.0.6 on 2024-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
