# Generated by Django 5.0.6 on 2024-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.IntegerField(blank=True, help_text='Leave Empty If Not Sale Product', null=True),
        ),
    ]
